fix(SkinManageDialog): add missing QMenu include
launcher/ui/dialogs/skins/SkinManageDialog.cpp: In member function ‘void SkinManageDialog::show_context_menu(const QPoint&)’:
launcher/ui/dialogs/skins/SkinManageDialog.cpp:344:18: error: variable ‘QMenu myMenu’ has initializer but incomplete type
  344 |     QMenu myMenu(tr("Context menu"), this);
      |                  ^~

Include appears to have been dropped transitively in either
0ba2c09787dbe3b852546dd24b437b832d575e4a or 45df360e4c751d30f8bfc38e5689f330e672492c

Signed-off-by: Alfred Wingate <parona@protonmail.com>